server {
    include /etc/nginx/includes/listen.conf;

    server_name arangodb.workspace.localhost arangodb.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://pp-ssh-tunnel-pod:8529;
    }
}
