server {
    include /etc/nginx/includes/listen.conf;

    server_name openhands.workspace.localhost openhands.workspace.fedora-workstation;

    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-openhands-pod:3000;
    }
}