server {
  include /etc/nginx/includes/listen.conf;
  server_name alex.pp.localhost;
  include /etc/nginx/includes/ssl.conf;

  resolver ${NGINX_RESOLVER};

  location / {
      set $upstream pp-pp3-frontend-pod:8090;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /pp-vendor {
      set $upstream pp-pp3-frontend-pod:8091;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /vendormodule {
      set $upstream pp-pp3-frontend-pod:8091;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /pp-public {
      set $upstream pp-pp3-frontend-pod:8092;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /public {
      set $upstream pp-pp3-frontend-pod:8092;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /pp {
      set $upstream pp-isms-frontend-pod:3004;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

  location /isms {
      set $upstream pp-isms-core-pod:4000;
      include /etc/nginx/includes/proxy.conf;
      proxy_pass http://$upstream;
  }

#   location /v1/custom-record-layout {
#       set $upstream pp-pp3-customservice-pod:8260;
#       include /etc/nginx/includes/proxy.conf;
#       proxy_pass http://$upstream;
#   }
}