server {
  include /etc/nginx/includes/listen.conf;
  server_name wordpress.website.localhost wordpress.website.workspace-gateway-pod;
  include /etc/nginx/includes/ssl.conf;

  resolver ${NGINX_LOCAL_RESOLVERS} valid=5s ipv6=off;
  resolver_timeout 2s;

  location / {
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_redirect off;

      set $upstream website-wordpress-pod:80;
      proxy_pass http://$upstream;
  }
}

server {
  include /etc/nginx/includes/listen.conf;
  server_name vite.website.localhost;
  include /etc/nginx/includes/ssl.conf;

  resolver ${NGINX_LOCAL_RESOLVERS};

  location / {
    include /etc/nginx/includes/proxy.conf;

    set $upstream website-wordpress-pod:5173;
    proxy_pass http://$upstream;
  }
}