{{ if has "pp3-frontend" .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pp3-frontend
  labels:
    app: {{ .Release.Name }}-pp3-frontend
spec:
  {{ if .Values.devmode }}
  strategy:
    type: Recreate
  {{ end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pp3-frontend
  template:
    metadata:
      annotations:
      {{ if .Values.devmode }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        app: {{ .Release.Name }}-pp3-frontend
        deployment: {{ .Release.Name }}-pp3-frontend
    spec:
      containers:
        - name: pp3-frontend
          image: localhost/pp3-frontend:latest
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          env:
            - name: EXTERNAL_URL
              value: alex.dev.privacyperfect.com
          volumeMounts:
            - name: {{ .Release.Name }}-pp3-frontend
              mountPath: /usr/src/app
      
      volumes:
        - name: {{ .Release.Name }}-pp3-frontend
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pp3-frontend

{{ end }}